variable "name" {
  description = "(Required) The name of the provider to create."
  type        = string

}

variable "saml_metadata_document" {
<<<<<<< HEAD
  description = "(Required) The name of the provider to create."
  type        = string

}

=======
  description = "(Required) An XML document generated by an identity provider that supports SAML 2.0."
  type        = string

}
>>>>>>> 04e81b62be3b37ce24698608ef6c47e67946a12f
