variable "region" {
  description = "aws region"
  type        = string
}

variable "vault_addr" {
  description = "vault address"
  type        = string
}

variable "vault_token" {
  description = "vault token"
  type        = string
}

variable "lease_seconds" {
  description = "The default TTL for credentials issued by this backend."
  type        = string
}

variable "backend" {
  description = "The path the AWS secret backend is mounted at, with no leading or trailing /s."
  type        = string
}

variable "role" {
  description = "The name to identify this role within the backend. Must be unique within the backend."
  type        = string

}

variable "enabled" {
  type        = bool
  description = "(Optional) A boolean flag to enable/disable the subscription. Defaults to true."
  default     = true
}

variable "event_categories" {
  type        = list(string)
  description = "(Optional) A list of event categories for a source_type that you want to subscribe to. Run aws neptune describe-event-categories to find all the event categories."
  default     = []
}

variable "name" {
  type        = string
  description = "(Optional) The name of the Neptune event subscription. By default generated by Terraform."
  default     = null
}

variable "name_prefix" {
  type        = string
  description = "(Optional) The name of the Neptune event subscription. Conflicts with name."
  default     = null
}

variable "sns_topic_arn" {
  type        = string
  description = "(Required) The ARN of the SNS topic to send events to."
}

variable "source_ids" {
  type        = list(string)
  description = "(Optional) A list of identifiers of the event sources for which events will be returned. If not specified, then all sources are included in the response. If specified, a source_type must also be specified."
  default     = []
}

variable "source_type" {
  type        = string
  description = "(Optional) The type of source that will be generating the events. Valid options are db-instance, db-security-group, db-parameter-group, db-snapshot, db-cluster or db-cluster-snapshot. If not set, all sources will be subscribed to."
  default     = null
}

variable "tags" {
  type        = map(string)
  description = "(Optional) A map of tags to assign to the resource. If configured with a provider default_tags configuration block present, tags with matching keys will overwrite those defined at the provider-level."
  default     = {}
}


variable "timeouts" {
  description = "aws_neptune_event_subscription provides the following Timeouts configuration options"
  type = object({
    create = string # (Default 40m) How long to wait for creating event subscription to become available.
    update = string # (Default 40m) How long to wait for updating event subscription to complete updates.
    delete = string # (Default 40m) How long to wait for deleting event subscription to become fully deleted.
  })
}