variable "region" {
  description = "aws region"
  type        = string

}
variable "vault_addr" {
  description = "vault address"
  type        = string
}
variable "vault_token" {
  description = "vault token"
  type        = string
}
variable "lease_seconds" {
  description = "The default TTL for credentials issued by this backend."
  type        = string
}
variable "backend" {
  description = "The path the AWS secret backend is mounted at, with no leading or trailing /s."
  type        = string
}
variable "role" {
  description = "The name to identify this role within the backend. Must be unique within the backend."
  type        = string

}

variable "name" {
  description = "(Required) The name of the provider to create."
  type        = string

}
variable "saml_metadata_document" {
  description = "(Required) An XML document generated by an identity provider that supports SAML 2.0."
  type        = string

}

variable "saml_metadata_document" {
  description = "(Required) The name of the provider to create."
  type        = string

}




