
variable "asg_name" {
  type        = string
  description = "The name of the auto scaling group. By default generated by Terraform."
}

variable "target_group_arn" {
  type        = string
  description = "aws_lb_target_group ARN, for use with Application/Network Load Balancing"
  default     = null
}

variable "elb_name" {
  type        = string
  description = "The name of the ELB (Classic Load Balancers)."
  default     = null
}