variable "action" {
  type        = string
  description = "(Required) The AWS Lambda action you want to allow in this statement."
}

variable "event_source_token" {
  type        = string
  description = "(Optional) The Event Source Token to validate. Used with Alexa Skills."
  default     = null
}

variable "function_name" {
  type        = string
  description = "(Required) Name of the Lambda function whose resource policy you are updating"

}

variable "principal" {
  type        = string
  description = "(Required) The principal who is getting this permission. e.g. s3.amazonaws.com, an AWS account ID, or any valid AWS service principal such as events.amazonaws.com or sns.amazonaws.com."

}

variable "qualifier" {
  type        = string
  description = "(Optional) Query parameter to specify function version or alias name. The permission will then apply to the specific qualified ARN. e.g. arn:aws:lambda:aws-region:acct-id:function:function-name:2"
  default     = null
}

variable "source_account" {
  type        = string
  description = "(Optional) This parameter is used for S3 and SES. The AWS account ID (without a hyphen) of the source owner."
  default     = null
}

variable "source_arn" {
  type        = string
  description = "(Optional) When the principal is an AWS service, the ARN of the specific resource within that service to grant permission to. Without this, any resource from principal will be granted permission – even if that resource is from another account. For S3, this should be the ARN of the S3 Bucket."
  default     = null
}

variable "statement_id" {
  type        = string
  description = "(Optional) A unique statement identifier. By default generated by Terraform."
  default     = null
}

variable "statement_id_prefix" {
  type        = string
  description = "(Optional) A statement identifier prefix. Terraform will generate a unique suffix. Conflicts with statement_id."
  default     = null
}