variable "region" {
  description = "aws region"
  type        = string
}

variable "vault_addr" {
  description = "vault address"
  type        = string
}

variable "vault_token" {
  description = "vault token"
  type        = string
}

variable "lease_seconds" {
  description = "The default TTL for credentials issued by this backend."
  type        = string
}

variable "backend" {
  description = "The path the AWS secret backend is mounted at, with no leading or trailing /s."
  type        = string
}

variable "role" {
  description = "The name to identify this role within the backend. Must be unique within the backend."
  type        = string

}

variable "name" {
  type        = string
  description = "(Required) The name of the new API Destination. The name must be unique for your account. Maximum of 64 characters consisting of numbers, lower/upper case letters, .,-,_."
}

variable "description" {
  type        = string
  description = "(Optional) The description of the new API Destination. Maximum of 512 characters."
  default     = null
}

variable "invocation_endpoint" {
  type        = string
  description = "(Required) URL endpoint to invoke as a target. This could be a valid endpoint generated by a partner service."
}

variable "http_method" {
  type        = string
  description = "(Required) Select the HTTP method used for the invocation endpoint, such as GET, POST, PUT, etc."
}

variable "invocation_rate_limit_per_second" {
  type        = number
  description = "(Optional) Enter the maximum number of invocations per second to allow for this destination. Enter a value greater than 0 (default 300)."
  default     = 300
}

variable "connection_arn" {
  type        = string
  description = "(Required) ARN of the EventBridge Connection to use for the API Destination."
}