variable "region" {
  description = "aws region"
  type        = string
}

variable "vault_addr" {
  description = "vault address"
  type        = string
}

variable "vault_token" {
  description = "vault token"
  type        = string
}

variable "lease_seconds" {
  description = "The default TTL for credentials issued by this backend."
  type        = string
}

variable "backend" {
  description = "The path the AWS secret backend is mounted at, with no leading or trailing /s."
  type        = string
}

variable "role" {
  description = "The name to identify this role within the backend. Must be unique within the backend."
  type        = string

}

variable "asg_name" {
  type        = string
  description = "The name of the auto scaling group. By default generated by Terraform."
}

variable "target_group_arn" {
  type        = string
  description = "aws_lb_target_group ARN, for use with Application/Network Load Balancing"
  default     = null
}

variable "elb_name" {
  type        = string
  description = "The name of the ELB (Classic Load Balancers)."
  default     = null
}